
language: node_js
node_js: stable
script: npm run build
notifications:
  email: true

deploy:
  provider: pages
  local_dir: ./dist
  skip_cleanup: true
  github_token: $REPO_TOKEN
  keep_history: true
  on:
    branch: master