
language: node_js 
node_js: stable
script: npm run build
notifications:
  email: false

deploy:
  provider: pages
  local_dir: ./dist
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master