
language: node_js
node_js: stable
#script: npm run build
script: ./deploy.sh

# deploy:
#   provider: pages
#   local_dir: ./dist
#   skip_cleanup: true
#   github_token: 776935011730878a0126d6eda4f9e403380eb705
#   keep_history: true
#   on:
#     branch: master