language: node_js 
node_js: stable

deploy:
  - provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local_dir: ./build

script: npm run build